# Generated by Django 3.1 on 2024-07-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240727_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
