# Generated by Django 3.1 on 2024-07-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
