# Generated by Django 3.1 on 2024-07-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20240725_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Productgallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
