# Generated by Django 4.2.14 on 2024-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imgaes_of_home', models.CharField(blank=True, max_length=50)),
                ('image_1', models.ImageField(upload_to='photos/products')),
                ('image_2', models.ImageField(upload_to='photos/products')),
                ('image_3', models.ImageField(upload_to='photos/products')),
                ('image_4', models.ImageField(upload_to='photos/products')),
                ('crousel_image_1', models.ImageField(upload_to='photos/crousel')),
                ('crousel_image_2', models.ImageField(upload_to='photos/crousel')),
                ('crousel_image_3', models.ImageField(upload_to='photos/crousel')),
                ('image_bottom_1', models.ImageField(upload_to='photos/products')),
                ('image_bottom_2', models.ImageField(upload_to='photos/products')),
                ('image_bottom_3', models.ImageField(upload_to='photos/products')),
                ('image_bottom_4', models.ImageField(upload_to='photos/products')),
                ('card_1_1', models.ImageField(upload_to='photos/crousel')),
                ('card_1_2', models.ImageField(upload_to='photos/crousel')),
                ('card_1_3', models.ImageField(upload_to='photos/crousel')),
                ('card_2_1', models.ImageField(upload_to='photos/crousel')),
                ('card_2_2', models.ImageField(upload_to='photos/crousel')),
                ('card_2_3', models.ImageField(upload_to='photos/crousel')),
                ('card_3_1', models.ImageField(upload_to='photos/crousel')),
                ('card_3_2', models.ImageField(upload_to='photos/crousel')),
                ('card_3_3', models.ImageField(upload_to='photos/crousel')),
            ],
        ),
    ]
